# This is a basic GitHub Actions workflow for a Continuous Deployment (CD) pipeline.

name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  validate-and-plan:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_HOPETONMON_COPY_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_HOPETONMON_COPY_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_AWS_REGION: "us-east-2"
      TF_VAR_AVAILABILITY_ZONE: "us-east-2a"
      TF_VAR_AVAILABILITY_ZONE2: "us-east-2b"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan

  deploy:
    needs: [validate-and-plan]
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_HOPETONMON_COPY_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_HOPETONMON_COPY_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_AWS_REGION: "us-east-2"
      TF_VAR_AVAILABILITY_ZONE: "us-east-2a"
      TF_VAR_AVAILABILITY_ZONE2: "us-east-2b"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          echo "Applying Terraform changes..."
          terraform apply -auto-approve